{{- if .Values.rsync.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pv-migrate.fullname" . }}-rsync
  namespace: {{ .Values.rsync.namespace }}
  labels:
    app.kubernetes.io/component: rsync
    {{- include "pv-migrate.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.rsync.backoffLimit }}
  template:
    metadata:
      {{- with .Values.rsync.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: rsync
        {{- include "pv-migrate.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.rsync.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pv-migrate.rsync.serviceAccountName" . }}
      restartPolicy: {{ .Values.rsync.restartPolicy }}
      securityContext:
        {{- toYaml .Values.rsync.podSecurityContext | nindent 8 }}
      containers:
        - name: rsync
          command:
            - sh
            - -c
            - |
              set -x
              n=0
              rc=1
              retries=10
              until [ "$n" -ge "$retries" ]
              do
                {{ required ".Values.rsync.command is required!" .Values.rsync.command }} {{ .Values.rsync.extraArgs }} && rc=0 && break
                n=$((n+1))
                echo "rsync attempt $n/10 failed, waiting 5 seconds before trying again"
                sleep 5
              done

              if [ $rc -ne 0 ]; then
                echo "rsync job failed after $retries retries"
              fi
              exit $rc
          securityContext:
            {{- toYaml .Values.rsync.securityContext | nindent 12 }}
          image: "{{ .Values.rsync.image.repository }}:{{ .Values.rsync.image.tag }}"
          imagePullPolicy: {{ .Values.rsync.image.pullPolicy }}
          resources:
            {{- toYaml .Values.rsync.resources | nindent 12 }}
          volumeMounts:
            {{- range $index, $mount := .Values.rsync.pvcMounts }}
            - mountPath: {{ $mount.mountPath }}
              name: vol-{{ $index }}
              readOnly: {{ default false $mount.readOnly }}
            {{- end }}
            {{- if .Values.rsync.privateKeyMount }}
            - mountPath: {{ .Values.rsync.privateKeyMountPath }}
              name: private-key
              subPath: privateKey
            {{- end }}
      nodeName: {{ .Values.rsync.nodeName }}
      {{- with .Values.rsync.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rsync.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rsync.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- range $index, $mount := .Values.rsync.pvcMounts }}
        - name: vol-{{ $index }}
          persistentVolumeClaim:
            claimName: {{ required ".Values.rsync.pvcMounts[*].pvcName is required!" $mount.name }}
            readOnly: {{ default false $mount.readOnly }}
        {{- end }}
        {{- if .Values.rsync.privateKeyMount }}
        - name: private-key
          secret:
            secretName: {{ include "pv-migrate.fullname" . }}-rsync
            defaultMode: 0400
        {{- end }}
{{- end }}
