apiVersion: v2
name: pv-migrate
description: The helm chart of pv-migrate
type: application
version: 0.5.0
appVersion: 0.5.0
home: https://github.com/utkuozdemir/pv-migrate
keywords:
  - pv-migrate
  - pvc
  - migration
sources:
  - https://github.com/utkuozdemir/pv-migrate
# icon: TBA
maintainers:
  - name: Utku Ã–zdemir
    email: utkuozdemir@gmail.com
    url: https://utkuozdemir.org
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: utkuozdemir/pv-migrate-sshd
      image: docker.io/utkuozdemir/pv-migrate-sshd:latest
    - name: utkuozdemir/pv-migrate-rsync
      image: docker.io/utkuozdemir/pv-migrate-rsync:latest
