---
name: Lint, build & test
on:
  push:
    branches:
      - master
      - renovate/**
    paths-ignore:
      - "**.md"
      - "img/**"
      - "test/**"
      - ".gitignore"
      - "docker/**"
      - "helm/**"
      - "renovate.json"
      - ".krew.yaml"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "img/**"
      - "test/**"
      - ".gitignore"
      - "docker/**"
      - "helm/**"
      - "renovate.json"
      - ".krew.yaml"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Install go
        uses: actions/setup-go@v3.0.0
        with:
          # renovate: go
          go-version: 1.17.5
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff --no-patch --exit-code
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@v0.2.1
      - name: Ensure code is properly formatted using gofumpt
        run: test -z "$(gofumpt -s -d .)"
      - name: Run linters
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          # renovate: golangci-lint
          version: v1.45.0
          skip-go-installation: true
          args: --timeout=3m0s
      - name: Build with Goreleaser
        if: ${{ always() }}
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          # renovate: goreleaser
          version: v1.6.3
          args: build --snapshot --rm-dist --single-target
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Install go
        uses: actions/setup-go@v3.0.0
        with:
          # renovate: go
          go-version: 1.17.5
      - name: Install richgo
        run: go install github.com/kyoh86/richgo@v0.3.10
      - name: Install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Install cilium-cli
        run: |
          wget https://github.com/cilium/cilium-cli/releases/download/v0.10.4/cilium-linux-amd64.tar.gz
          sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
          rm cilium-linux-amd64.tar.gz

      - name: kind-1 - Create cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: kind-1
          version: v0.11.1
          node_image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
          config: test/kind-config.yaml
      - name: kind-1 - Create metallb-system namespace
        run: kubectl create namespace metallb-system --dry-run=client -oyaml | kubectl apply -f -
      - name: kind-1 - Install allow-all network policies on system namespaces
        run: |
          kubectl -n kube-system apply -f test/netpol-allow-all.yaml
          kubectl -n local-path-storage apply -f test/netpol-allow-all.yaml
          kubectl -n metallb-system apply -f test/netpol-allow-all.yaml
      - name: kind-1 - Install Cilium with default-deny policy
        run: cilium install --config enable-policy=always
      - name: kind-1 - Install MetalLB
        run: |
          IP_RANGE_PREFIX=$(docker network inspect -f '{{(index .IPAM.Config 0).Subnet}}' kind | cut -d. -f1-3)
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade metallb \
          --install bitnami/metallb \
          --namespace metallb-system \
          --version 2.5.14 \
          --atomic \
          --values test/metallb-values.yaml \
          --set configInline.address-pools[0].addresses[0]=${IP_RANGE_PREFIX}.240-${IP_RANGE_PREFIX}.255
          helm -n metallb-system get values metallb
      - name: kind-1 - Wait for all pods in the cluster to be ready
        run: kubectl wait pod --for=condition=Ready --all --all-namespaces

      - name: kind-2 - Create cluster
        uses: helm/kind-action@v1.2.0
        env:
          KUBECONFIG: /home/runner/.kube/kind-2.yaml
        with:
          cluster_name: kind-2
          version: v0.11.1
          node_image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
          config: test/kind-config.yaml
      - name: kind-2 - Install allow-all network policies on system namespaces
        run: |
          kubectl -n kube-system apply -f test/netpol-allow-all.yaml
          kubectl -n local-path-storage apply -f test/netpol-allow-all.yaml
        env:
          KUBECONFIG: /home/runner/.kube/kind-2.yaml
      - name: kind-2 - Install Cilium with default-deny policy
        run: cilium install --config enable-policy=always
        env:
          KUBECONFIG: /home/runner/.kube/kind-2.yaml
      - name: kind-2 - Wait for all pods in the cluster to be ready
        run: kubectl wait pod --for=condition=Ready --all --all-namespaces
        env:
          KUBECONFIG: /home/runner/.kube/kind-2.yaml

      - name: Run tests
        env:
          RICHGO_FORCE_COLOR: "1"
          PVMIG_TEST_EXTRA_KUBECONFIG: /home/runner/.kube/kind-2.yaml
        run: richgo test -coverpkg=./... -coverprofile=profile.cov -covermode=count -timeout 20m -v ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1.5.1
        with:
          path-to-profile: profile.cov
          shallow: true
