---
name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          # to be able to generate the full changelog:
          # https://github.com/goreleaser/goreleaser-action/issues/56#issuecomment-568718162
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
      - name: Login to DockerHub
        uses: docker/login-action@v3.7.0
        with:
          username: utkuozdemir
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v7.0.0
        with:
          # renovate: depName=goreleaser/goreleaser datasource=github-releases
          version: v2.14.1
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_ACCESS_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
      - name: Update new version in krew-index
        if: ${{ !contains(github.ref_name, '-') }}
        uses: rajatjindal/krew-release-bot@v0.0.50

  release-images:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image:
          - name: pv-migrate-rsync
            context: ./docker/rsync/
          - name: pv-migrate-sshd
            context: ./docker/sshd/
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.7.0
        with:
          username: utkuozdemir
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine tags
        id: tags
        run: |
          TAGS="docker.io/utkuozdemir/${{ matrix.image.name }}:${{ github.ref_name }}"
          TAGS="${TAGS},ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" != *-* ]]; then
            TAGS="${TAGS},docker.io/utkuozdemir/${{ matrix.image.name }}:latest"
            TAGS="${TAGS},ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:latest"
          fi
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v6.19.2
        with:
          context: ${{ matrix.image.context }}
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
