---
name: release-sshd-image
on:
  push:
    tags:
      - docker-sshd-*
jobs:
  release-sshd-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: utkuozdemir
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set image tag as env variable
        run: echo "IMAGE_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/^docker-sshd-//')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./docker/sshd/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/utkuozdemir/pv-migrate-sshd:latest
            docker.io/utkuozdemir/pv-migrate-sshd:alpine-3-${{ env.IMAGE_VERSION }}
